/*
 * IPFS API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Peer struct {
	Id string `json:"id"`
	PublicKey string `json:"publicKey"`
	Addresses Peers `json:"addresses"`
	AgentVersion string `json:"agentVersion"`
	ProtocolVersion string `json:"protocolVersion"`
	RepoVersion float32 `json:"repoVersion,omitempty"`
}
