/*
 * IPFS API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type SubscribeToPubsubTopicPayload struct {
	Topic string `json:"topic"`
	Discover bool `json:"discover,omitempty"`
}
