/*
 * IPFS API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type RepoStats struct {
	NumObjects int32 `json:"numObjects,omitempty"`
	RepoSize int32 `json:"repoSize,omitempty"`
	RepoPath string `json:"repoPath"`
	Version int32 `json:"version,omitempty"`
	StorageMax int32 `json:"storageMax,omitempty"`
}
