/*
 * IPFS API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type RemotePeer struct {
	Id string `json:"id"`
	Address string `json:"address"`
	PublicKey string `json:"publicKey,omitempty"`
	Latency string `json:"latency,omitempty"`
}
