/*
 * IPFS API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type IpnsOptions struct {
	Value string `json:"value"`
	// Resolve given path before publishing
	Resolve bool `json:"resolve,omitempty"`
	// Time duration of the record
	Lifetime string `json:"lifetime,omitempty"`
	// Time duration this record should be cached
	Ttl string `json:"ttl,omitempty"`
	// Name of the key to be used or Peer ID
	Key string `json:"key,omitempty"`
}
