/*
 * IPFS API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Blocks struct {
	Sent int32 `json:"sent,omitempty"`
	Received int32 `json:"received,omitempty"`
	Duplicate int32 `json:"duplicate,omitempty"`
}
