/*
 * IPFS API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type BitswapLedger struct {

	Peer string `json:"peer,omitempty"`

	DebtRatio float32 `json:"debtRatio,omitempty"`

	Sent int32 `json:"sent,omitempty"`

	Received int32 `json:"received,omitempty"`

	Exchanges int32 `json:"exchanges,omitempty"`
}
