/*
 * IPFS API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Pong struct {

	Success bool `json:"success,omitempty"`

	Time int32 `json:"time,omitempty"`

	Text string `json:"text,omitempty"`
}
