/*
 * IPFS API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GenerateKeypairPayload struct {

	Name string `json:"name"`

	// base64 encoded PKCS #8 PEM file to import keypairs from
	Pem string `json:"pem,omitempty"`

	// Password to PKCS #8 PEM file
	Password string `json:"password,omitempty"`
}
